version: '3.4'

services:
  
  proxy:
    image: nginx:1.14-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - keycloak
    networks:
      - security

  db:
    image: postgres:9.6.9-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME-keycloak}
      POSTGRES_USER: ${DB_USER-keycloak}
      POSTGRES_PASSWORD: ${DB_PWD-keycloak}
    networks:
      - security

  keycloak:
    image: keycloak:4.1.0.Final.Proxy
    restart: always
    environment:
      KEYCLOAK_USER: ${KC_USER-admin}
      KEYCLOAK_PASSWORD: ${KC_PWD-admin}
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_NAME-keycloak}
      DB_USER: ${DB_USER-keycloak}
      DB_PASSWORD: ${DB_PWD-keycloak}
      PROXY_ADDRESS_FORWARDING: "true"
    links:
      - db
    networks:
      - security

networks:
  security: