version: '3.4'

services:

  db:
    image: postgres:9.6.9-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME-keycloak}
      POSTGRES_USER: ${DB_USER-keycloak}
      POSTGRES_PASSWORD: ${DB_PWD-keycloak}
    networks:
      - security

  keycloak:
    image: keycloak:4.1.0.Final.CustomTheme
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: ${KC_USER-admin}
      KEYCLOAK_PASSWORD: ${KC_PWD-admin}
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_NAME-keycloak}
      DB_USER: ${DB_USER-keycloak}
      DB_PASSWORD: ${DB_PWD-keycloak}
    links:
      - db
    networks:
      - security

networks:
  security: